version: 2.1

parameters:
  boot-version:
    type: string
    description: "The version of the JDK to test against"
    default: "2.8.2"
  clojure-version:
    type: string
    description: "The version of the JDK to test against"
    default: "1.10.1"
  cache_version:
    type: string
    description: "Change this value to force a cache update"
    default: "1"

# CircleCI maintains a library of pre-built images
# documented at https://circleci.com/docs/2.0/circleci-images/
executors:
  openjdk-8:
    docker:
      - image: circleci/clojure:openjdk-8-boot-<< pipeline.parameters.boot-version >>
  openjdk-11:
    docker:
      - image: circleci/clojure:openjdk-11-boot-<< pipeline.parameters.boot-version >>

jobs:
  test-and-build:
    parameters:
      jdk-executor:
        description: "The Boot/JDK executor to use"
        type: executor

    executor: << parameters.jdk-executor >>
    environment:
      # Customize the JVM maximum heap limit
      BOOT_JVM_OPTIONS: -Xmx3200m
      BOOT_CLOJURE_VERSION: << pipeline.parameters.clojure-version >>
      BOOT_WATCHERS_DISABLE: yes
      BOOT_VERSION: << pipeline.parameters.boot-version >>
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: shasum "build.boot" | awk '{print $1}' > clojure_cache_seed
      - restore_cache:
          key: clojure-<< pipeline.parameters.cache_version >>-{{ checksum "clojure_cache_seed" }}
      - run:
          name: Test and Build
          command: boot --no-profile test build target
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache
          key: clojure-<< pipeline.parameters.cache_version >>-{{ checksum "clojure_cache_seed" }}
      - persist_to_workspace:
          root: /tmp
          paths:
            - target/perun-*.jar
            - version.properties
            - clojure_cache_seed

  deploy:
    executor: openjdk-8
    environment:
      # Customize the JVM maximum heap limit
      BOOT_JVM_OPTIONS: -Xmx3200m
      BOOT_CLOJURE_VERSION: << pipeline.parameters.clojure-version >>
      BOOT_WATCHERS_DISABLE: yes
      BOOT_VERSION: << pipeline.parameters.boot-version >>
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: clojure-<< pipeline.parameters.cache_version >>-{{ checksum "clojure_cache_seed" }}
      - run:
          name: Publish Snapshot to Clojars
          command: |
            jar_file=$(find target -name 'perun*.jar')
            boot --no-boot-script --no-profile --exclude-clojure \
                 --dependencies 'degree9/boot-semver:1.10.0' \
                 --init '(require (quote [degree9.boot-semver :refer [push-snapshot]]))' \
                 version push-snapshot --file "$jar_file"

workflows:
  version: 2
  build-test-deploy-on-tag:
    jobs:
      - test-and-build:
          name: test-and-build-<< matrix.jdk-executor >>
          matrix:
            parameters:
              jdk-executor: ["openjdk-8"]
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([a-zA-Z0-9]+))?/
      - deploy:
          requires:
            - test-and-build
          filters:
            # only act on version tags
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([a-zA-Z0-9]+))?/
            # runs for no branches
            branches:
              ignore: /.*/
